Correct overcloud password docs
openstack-k8s-operators/osp-director-dev-tools pull request #155
Opened 2021-06-24 18:29 UTC by dprince

2021-06-30 14:09 UTC, mpryc commented
May I ask to rebase this change? I have not implemented yet rebase before CI run which we've discussed.

2021-07-01 09:21 UTC, stuggi requested changes

2021-07-01 09:21 UTC, stuggi commented on ansible/README.md
> +| Pwd | The admin password can be found in the `/home/cloud-admin/tripleo-deploy/clouds.yaml` file on the `openstackclient` pod in the `openstack` namespace. |
with https://github.com/openstack-k8s-operators/osp-director-operator/pull/289/files this is now at the default location for user specific `clouds.yaml` at `/home/cloud-admin/.config/openstack/clouds.yaml`

2021-07-01 09:21 UTC, stuggi commented on ansible/README.md
> +oc exec -it openstackclient -- cat /home/cloud-admin/tripleo-deploy/clouds.yaml | grep -w password
`/home/cloud-admin/.config/openstack/clouds.yaml`

2021-07-09 12:35 UTC, dprince commented
> May I ask to rebase this change? I have not implemented yet rebase before CI run which we've discussed.

Yes. I will rebase and fix it now.

2021-07-09 12:37 UTC, dprince commented on ansible/README.md
> +| Pwd | The admin password can be found in the `/home/cloud-admin/tripleo-deploy/clouds.yaml` file on the `openstackclient` pod in the `openstack` namespace. |
@stuggi got it, thanks!

2021-07-09 14:33 UTC, stuggi approved these changes
/lgtm

2021-07-12 16:04 UTC, stuggi approved these changes
/lgtm

2021-07-13 06:33 UTC, merged