Increase sts timeout
openstack-k8s-operators/osp-director-dev-tools pull request #437
Opened 2022-12-09 01:36 UTC by olliewalsh

2022-12-09 06:43 UTC, stuggi approved these changes
/lgtm

2022-12-09 10:41 UTC, olliewalsh commented on ansible/osp_sts.yaml
> +        oc exec -t -n openstack openstackclient -- /bin/bash -c "source /home/cloud-admin/ansible_ha.env && pushd {{ sts_test_dir }} && timeout {{ osp.deploy_timeout * 2 }} sh osp_operator_sanity_run
doh, it's "90m" so can't just multiply it

2022-12-12 11:17 UTC, olliewalsh commented on ansible/osp_sts.yaml
> +        oc exec -n openstack openstackclient -- bash -c "sed -i -e 's/timeout_seconds=180/timeout_seconds=600/g' -e 's/EXTERNAL_NET_NAME=.*/EXTERNAL_NET_NAME=public/g' {{ sts_test_dir }}/templates/bo
Fetching the external net name was failing with a 503 Service Unavailable error, I expect it is just a timing issue. For now I've just hard-coded it

2022-12-12 11:18 UTC, olliewalsh commented on ansible/osp_sts.yaml
> +  - name: Skip if first run
If we run sts before minor update it leaves a test db behind and the minor update fails, so skipping this step for now

2022-12-13 07:03 UTC, pinikomarov requested changes
LGTM , and please drop the : 
tasks : 
  - name: Mark this is the first run
  - name: Skip if first run
  the fix for those was merged

2023-04-25 14:38 UTC, closed without merging