Add DMBS deployment
openstack-k8s-operators/osp-director-dev-tools pull request #457
Opened 2023-03-24 17:21 UTC by krcmarik

The PR adds Cinder in A/A on the Edge site and Glance multistore. The central site redeploy with updated configuration for ceph cluster on the site and glance multistore is required. It's needed to create an raw image in all the glance stores to test such deployment with tempest. Unfortunately openstack client does not support that and tempest image does not include qemu-img to covert the image to raw format directly on the tempest pod.

2023-04-24 16:00 UTC, olliewalsh commented on ansible/osp_redeploy_dcn_central.yaml
> +    custom_config_action: redeploy
that "action" is still a deploy so I think using a separate file for this would be the better option

2023-04-27 10:59 UTC, olliewalsh commented on ansible/templates/osp/tripleo_heat_envs/features/common/dmbs/glance.yaml.j2
> +{% if "dcn" in config_custom_ceph_cluster_name|default('')  %}
might be better to make this explicit instead of the name magically changing behaviour (could be extremely confusing), e.g config_custom_dcn_remote_site = true/false

2023-04-30 20:42 UTC, krcmarik commented on ansible/osp_redeploy_dcn_central.yaml
> +    custom_config_action: redeploy
I honestly do not know how to include a separate heat file only during the redeploy of the stack without doing some significant changes in osp_custom_config.yaml playbook. It would be more explicit to take the glance store config for dcn1 out to a seprate file with:
```
  GlanceMultistoreConfig:
    dcn1:
      GlanceBackend: rbd
      GlanceStoreDescription: 'dcn1 rbd glance store'
      CephClientUserName: 'openstack'
      CephClusterName: dcn1
```

But I do not know how to include it only during the redeploy easily.

2023-05-04 10:20 UTC, olliewalsh commented on ansible/osp_redeploy_dcn_central.yaml
> +    custom_config_action: redeploy
I'll create a PR to support this...

2023-05-04 10:36 UTC, olliewalsh commented on ansible/osp_redeploy_dcn_central.yaml
> +    custom_config_action: redeploy
Not tested this yet but I think it should work https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/468
So could then create something like `templates/osp/tripleo_heat_envs/features/common/dmbs_store_dcn1/dcn1_store.yaml` and set `config_custom_extrafeatures: ["dmbs_store_dcn1"]` in the redeploy vars

2023-05-04 10:56 UTC, krcmarik commented on ansible/osp_redeploy_dcn_central.yaml
> +    custom_config_action: redeploy
Thanks, I'll test that and let you know/update the other PR based on this one.

2023-05-05 15:11 UTC, olliewalsh commented on ansible/osp_redeploy_dcn_central.yaml
> +    custom_config_action: redeploy
FYI CI is hitting https://bugzilla.redhat.com/show_bug.cgi?id=1840886#c9, workaround in https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/467

2023-05-08 17:36 UTC, krcmarik commented
The PR depends on the PR #468

2023-05-09 11:19 UTC, olliewalsh requested changes

2023-05-09 11:19 UTC, olliewalsh commented on ansible/osp_deploy_dcn_1.yaml
> +    custom_config_dmbs_remote_site: "{{ 'true' if 'dmbs' in osp.extrafeatures else 'false' }}"
If 'false' is interpreted as a string it would be true (non-empty string is true, at least in python). Think you could just use `"{{ 'dmbs' in osp.extrafeatures }}"`

2023-05-09 13:05 UTC, krcmarik commented on ansible/osp_deploy_dcn_1.yaml
> +    custom_config_dmbs_remote_site: "{{ 'true' if 'dmbs' in osp.extrafeatures else 'false' }}"
It seems to be interpreted as a correct boolean based on my testing in {{ 'true' if 'dmbs' in osp.extrafeatures else 'false' }} expression which means If no 'dmbs' in extrafeatures the false boolean is returned but the "{{ 'dmbs' in osp.extrafeatures }}" expression works too, I'll update the PR. Thanks

2023-05-30 14:49 UTC, olliewalsh approved these changes

2023-05-30 15:00 UTC, olliewalsh requested changes

2023-05-30 15:00 UTC, olliewalsh commented on ansible/vars/17.1_dcn_dmbs.yaml
> +      # The scenario/tests create an image which is not in raw format and/or not in DCN site's store which causes the test to fail
Looks like the cause of one of the test failures in the CI job too - need to add `tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_instance_hard_reboot_after_vol_snap_deletion` ?

2023-05-30 17:57 UTC, abays reviewed
+1 from me if we can get CI passing

2023-05-31 04:24 UTC, krcmarik commented on ansible/vars/17.1_dcn_dmbs.yaml
> +      # The scenario/tests create an image which is not in raw format and/or not in DCN site's store which causes the test to fail
That's true, the two tests which failed and were not failing due to bugs, I forgot to add. Thanks

2023-05-31 15:48 UTC, olliewalsh approved these changes

2023-05-31 15:49 UTC, merged