install RH CA on OSP nodes
openstack-k8s-operators/osp-director-dev-tools pull request #467
Opened 2023-05-04 09:41 UTC by pinikomarov

- Set branch in pr pipeline
- fix_pull_request_jobs_name
- Remove OSP17 libvirt workaround as use now RHEL9
- Rely on ooo neutron defaults
- Remove block to cleanup /etc/containers/registries.conf
- Use trusted zone for ospnetwork and make sure not to nat
- Remove OS::TripleO::Services::Rear from roles
- install fence agents also on ControllerSriov role
- use ctlplane_host_routes for ctlplane interfarce routes
- [workaround] Fixes for deployed-network-environment.j2.yaml
- [workaround] add ipv6 support for deployed-network-environment.j2.yaml
- make sure ip forwarding is enabled for ipv4 and ipv6
- remove workaround for https://review.opendev.org/c/openstack/tripleo-heat-templates/+/832520
- Also set ip6 GW address on the ext bridge to allow switch deployments
- Enable phase2 tempest tests
- Switch all OSP17 configs to use passed_phase2
- In ansible 2.9 it is nmcli, not community.general.nmcli
- disable block_migration_for_live_migration for hci
- fix tempest_disable_feature_dict in tempest script template
- Change project_network_v6_cidr to 2001:db8:fd01::/48
- Remove some tempest settings and use the defaults
- Disable phase2 tempest tests
- Enable phase2 tempest test for 17.0_ipv6_subnet.yaml
- Disable tests which test fip or required fip to validate for ipv6
- Disable Tests which expect to be able to set static external IP for IPv6
- Disable live migration test with trunk for IPv6
- bump OCP to 4.10.27 and CNV 4.10 (#405)
- Expose arbitrary inclusion of pre-existing heat env files (#406)
- Stop using grubby to alter the kernel cmdline on the guest image
- Increase timeout when waiting for hosts to come online
- cleanup transiet ospnetwork nm vlan confs
- Use CHANGE_TARGET as PR target branch
- Workaround kernel cmdline insanity
- Add support for ansible-sts test framework to verify OSP HA
- fix junit.xml report creation
- remove workaround for BZ2087231
- Update CentOS 9 stream VM image
- Disable network-feature-enabled.floating_ips for ipv6 (#419)
- Sriov hybrid templates  (#407)
- Dpdk hybrid templates  (#408)
- Pin bcrypt to <4.0.0
- Move enableFencing to OpenStackConfigGenerator
- Remove mysqld and replace with mariadbd for 17+ and remove retries for wait for pod
- Use latest osconfigversion for osdeploy
- remove mpryc from OWNERS file
- Rebase AI installs against latest Crucible
- Fix reviews
- nfv templates1
- STF support for 16.2
- nfv templates1
- ocp_master add cpu and mem
- [OSPK8-647] Clean OSBMS first during 'make openstack_cleanup' (#431)
- default to latest_cdn_osp_puddle
- Ignore errors from nmcli module when deleting bridges
- Filter configversions on configgenerator name
- Regenerate config using new t-h-t for minor update converge
- Add 16.2.3_fencing vars
- Ignore errors when polling openstackclient status
- Workaround BZ2087231 for 16.2.3
- Add osp17.0 fencing profile
- Use custom index for osp17 ha testing
- Some fixes (#440)
- changes based on pr440 for osp17
- Increase sts timeout
- copy sts log directory to localhost for collecting
- truncate /etc/machine-id in golden image (#442)
- Disable some tempest tests for 17.0_hci_subnet
- Allow pool_ids or pool regex to be used for rhsm
- Use passed_phase2 for 17.0 RHEL9 jobs
- Support for OCP 4.11 and 4.12
- Run sushy-tools in a virtualenv and upgrade to latest version
- Update crucible to latest commit and remove workaround for sushy-tools bugs
- Add missing python headers to build python-libvirt
- Always apply provisionserver yaml, image may have changed in vars
- Switch from oc replace to oc patch
- Render version independent feature yaml
- Stop rendering extrafeatures tarball config
- Make virt-customize task atomic
- DCN with HCI example
- Configure nova AZs for DCN
- Run cell_v2 discovery for dcn
- Add make var to specify openstack deployment scenario
- Replace shell backticks with $()
- Fix OCP AI version selection
- Fix typo and storage-backend indent
- No longer necessary to filter unused roles
- Remove 17.0 dcn ssh firewall workaround
- Update wallaby centos base image
- Add missing gcc dependency to README (#452)
- Generate an SSH key for OCP connection (#453)
- Choose registry-proxy mirror based on current domain (default to rdu)
- Use registry proxy in osp_release_auto too
- Use local DNS server for each site and remove dead server
- Gather minimum facts for ocp_ai_prep to get ansible_nodename
- Use local qe mirror for rhos-release
- Create a quickstart procedure (#456)
- add gcc as sushy-tools dep
- just restructure Makefile and add help output
- Update CentOS-8 stream image
- Update CentOS-9 stream image
- 4.12 master/worker workaround
- initial 17.1 enablement
- update 17.0 rhel-9 image
- Revert "4.12 master/worker workaround"
- update crucible reference to 85ad8f8a98a7c43ad0f46d3fc2e99f792b37b43f
- Fix selinux denial when running scripts to manage freeipa
- add additional 17.1 scenario vars
- install_RH_CA_on_OSP_nodes

2023-05-04 09:54 UTC, pinikomarov commented
before : 

`[root@controllersriov-0 ~]# dnf repository-packages  rhelosp-ceph-5-tools list
RHOS Release Brew                                              0.0  B/s |   0  B     00:01
Errors during downloading metadata for repository 'rhos-release-brew':
- Curl error (60): SSL peer certificate or SSH remote key was not OK for https://download-node-02.eng.bos.redhat.com/brewroot/repos/rhostools-rhel-8/latest/x86_64/repodata/repomd.xml [SSL certificate problem: unable to get local issuer certificate]`

after : 

`[cloud-admin@openstackclient ~]$ ansible -i ./ctlplane-ansible-inventory ControllerSriov -mshell -a'dnf repository-packages  rhelosp-ceph-5-tools list|head -n 2 '
172.22.0.103 | CHANGED | rc=0 >>
Red Hat Enterprise Linux Fast Datapath 9 - x86_  50 kB/s | 128 kB     00:02
Red Hat Enterprise Linux Fast Datapath 9 - x86_  37 kB/s |  27 kB     00:00
172.22.0.104 | CHANGED | rc=0 >>
Red Hat Enterprise Linux Fast Datapath 9 - x86_  51 kB/s | 128 kB     00:02
Red Hat Enterprise Linux Fast Datapath 9 - x86_  37 kB/s |  27 kB     00:00
172.22.0.102 | CHANGED | rc=0 >>
Red Hat Enterprise Linux Fast Datapath 9 - x86_  50 kB/s | 128 kB     00:02
Red Hat Enterprise Linux Fast Datapath 9 - x86_  37 kB/s |  27 kB     00:00`

2023-05-05 14:22 UTC, pinikomarov commented
CI testing here : https://url.corp.redhat.com/e2c5e9e

2023-05-05 14:42 UTC, olliewalsh requested changes

2023-05-07 07:44 UTC, pinikomarov commented on ansible/templates/osp/rhsm.yaml.j2
> +      curl -O https://password.corp.redhat.com/RH-IT-Root-CA.crt
so If I understand correctly , when 
[Manage CA certificates using ansible ](https://review.opendev.org/c/openstack/tripleo-heat-templates/+/839296) is merged we'll no longer need this W/A right ? 
when would that be for 17 ? since the bz is on won't fix on 16.. 

Agree about the flag .

Even if we already have the cert in repo , we would need to copy in to the openstackclient and then copy to all controllers , isn't it more simple to download it individually for each ?

2023-05-07 10:16 UTC, pinikomarov commented
> CI testing here : https://url.corp.redhat.com/e2c5e9e

fyi with this w/a jobs are passing ^^ , although it's still a draft currently

2023-05-08 05:51 UTC, stuggi commented on ansible/templates/osp/rhsm.yaml.j2
> +      curl -O https://password.corp.redhat.com/RH-IT-Root-CA.crt
@olliewalsh I don't think that patch will fix the issue for us. e.g. if fencing is enabled, register_overcloud_nodes runs fencing_prep which installs fence_kubevirt package before the ooo deployment. 

As you mentioned we already have the cert file, so what should also work is https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/469 to add the file to the base image used for vmset  and bmset

2023-05-08 08:30 UTC, pinikomarov commented on ansible/templates/osp/rhsm.yaml.j2
> +      curl -O https://password.corp.redhat.com/RH-IT-Root-CA.crt
ok then we can close this pr ? 
do we have any need for this approach ?

2023-05-09 06:42 UTC, closed without merging