stf repo url fix
openstack-k8s-operators/osp-director-dev-tools pull request #540
Opened 2024-07-30 22:25 UTC by pinikomarov

- **remove iscsi from tempest secondary volume backend**
- **Use latest OCP and CNV version**
- **Fix - Untar oc non rerunable**
- **Switch to the 0.5.2 cirros for DMBS deployments**
- **allow tempest succesive runs**
- **Set cirros-0.5.2 as default image for tempest**
- **remove wrong osp_rhos_release_compose in vars/wallaby_subnet.yaml**
- **Move openstackclient FreeIPA cleanup to openstack_cleanup target**
- **remove ocp client tmp files as root**
- **Add proxy vars to configure OCP cluster wide proxy**
- **add 16.2.4_fencing and 16.2.5_fencing vars**
- **Follow up to PR#502**
- **fix storage_mgmt network route**
- **Improve overall OCP version support and add 4.13**
- **set sefault osp puddle to passed_phase2**
- **Pin sushy-tools < 0.21.1 to avoid VM boot problems**
- **ffu initial**
- **added stuff**
- **fix typo**
- **Partial FFU to 17.1 RHEL 8.4, no ceph**
- **FFU Controller RHEL upgrade**
- **Reboot nodes after minor update**
- **Remove configgenerator instances when switching operator version**
- **Fix grub default**
- **Add compute upgrade and update to latest LeappInitCommand**
- **Update UpgradeLeappDevelSkip param**
- **Handle HA controllers**
- **Pass FFU compose ID from Makefile to avoid FFU specific vars files**
- **Support 17/cephadm in node reboot logic**
- **Add vars files to test FFU with  (pretty much)**
- **Fix reboot syntax error**
- **Add ceph 4-5 upgrade and cephadm adopt**
- **dnf update nodes before initial deployment by default**
- **Add missing OCP creds to osp_ceph_update playbook**
- **Reboot after dnf update**
- **Fix ceph image overrides**
- **Include network vars when rendering config**
- **Must use el8 image for ceph-ansible**
- **Need to install cephadm in UpgradeInit**
- **Update to latest Leapp params**
- **Cache osp auto dict**
- **Switch to 17.1 el9 openstackclient before update prepare**
- **Move one HCI back to leaf2**
- **Fix indent issue in rhsm template**
- **Back to single leaf, need to debug ceph issue with spine & leaf**
- **Ignore deploy errors for ceph-upgrade for now**
- **Fix when condition**
- **Add final libvirt container switch-a-roo deployment**
- **Add tempest conf for 16.2/17.1_fencing_ipv6_hci_tlse_subnet envs**
- **DeployedCeph should be false**
- **Use 17.1-rhel8-tripleoclient from the compose**
- **Patch for BZ2237743 until it lands downstream**
- **Add support NFS backend for nova and cinder**
- **Multi-rhel FFU support**
- **Disable workaround for BZ2226845**
- **Need lifecycle/upgrade-prepare.yaml for FFU**
- **Disable nova version check during regular FFU**
- **Add missing cinder NFS export**
- **Remove redundant combine() in config_generator_role_overrides***
- **Generate Rhel8 roles for all Compute roles**
- **Use correct configversion for container-upgrade deployment**
- **Workaround nova NFS volume mount issue**
- **Generate multi-rhel container image params for system-update too**
- **Add reference to rhel guest image bug/kb**
- **Ceph OSDs on different subnets now works**
- **Skip multirhel compute tasks when no computes remain**
- **Need 2+ computes for each role for multirhel FFU**
- **set opm url path**
- **Fix yaml indent when ceph_extraconfig_network is not defined**
- **remove BZ2237743 feature from 17.1_fencing and 17.1_fencing_nfs**
- **stf templates (#516)**
- **add missing stf hci 16.2 job vars**
- **Wait for BMHs to become available during compute provisioning**
- **updated 17.1 tlse subnet to p2**
- **Fix for https://issues.redhat.com/browse/OSPRH-3411 (#523)**
- **enable ocatavia in 17.1_subnet**
- **Add support for OCP 4.14 (#528)**
- **bump ocp worker memory to 35G**
- **Incrase 128gb RWO pvs to 8**
- **fix retry on failing patch csv**
- **increase 128gb RWX pvs to 10**
- **[cnv] disable import of default images**
- **Workaround BZ2235206**
- **Remove workaround for BZ2170021 in 17.1**
- **Remove gnocchi from 17.x STF config**
- **Fix external bridge name so it works with OVNKubernetes clusters**
- **Wait until AI OCP cluster is stable after installation (#539)**
- **[OSPK8-812] Use a more reliable root device hint for computes (#538)**
- **fix stf tests repo url**

2024-07-31 03:33 UTC, lnatapov requested changes
We should checkout branch old_stf_job
git clone -b old_stf_job https://github.com/infrawatch/feature-verification-tests.git

2024-07-31 05:50 UTC, lnatapov approved these changes
LGTM

2024-07-31 08:52 UTC, olliewalsh requested changes

2024-07-31 08:52 UTC, olliewalsh commented on ansible/osp_stf_tests.yaml
> +      oc exec -n openstack openstackclient -- bash -c "test -d /home/cloud-admin/feature-verification-tests || (pushd /home/cloud-admin/ && git clone -b old_stf_job -c http.sslVerify=false https://gi
`http.sslVerify=false` needs to be removed, if github.com fails SSL verification do not pull code from it!!!

2024-08-07 14:51 UTC, olliewalsh commented
Re-running CI on this, failed with DNS issues

2024-08-12 21:33 UTC, pinikomarov commented
@olliewalsh so this is good to go correct ? 
cc: @lnatapov

2024-08-12 22:00 UTC, merged