Create shared provisionserver
openstack-k8s-operators/osp-director-dev-tools pull request #62
Opened 2021-02-11 19:02 UTC by dprince

This uses the new ProvisionServerName feature on BaremetalSet
to leverage use of a pre-created ProvisionServer when creating
the CR. Should speed up subsequent deployments of BaremetalSets.

2021-02-11 19:02 UTC, dprince commented
This won't pass until we land: https://github.com/openstack-k8s-operators/osp-director-operator/pull/147

2021-03-04 07:11 UTC, stuggi requested changes

2021-03-04 07:11 UTC, stuggi commented on ansible/install_computes.yaml
> +      oc get osprovserver openstack -o json --ignore-not-found
should add -n openstack

2021-03-04 12:12 UTC, dprince commented on ansible/install_computes.yaml
> +      oc get osprovserver openstack -o json --ignore-not-found
got it in latest commit, thanks!

2021-03-04 12:23 UTC, stuggi approved these changes
/lgtm

2021-03-04 20:05 UTC, merged