rhel-subscription does not need to be mandatory
openstack-k8s-operators/osp-director-dev-tools pull request #81
Opened 2021-03-15 11:55 UTC by jlarriba

This PR does not need to go through if you think it is an option you do not want to give, but it is pretty useful for me, so I thought I might help others too. Feel free to dismiss if it is not something you would like.

Currently, passing a rhel subscription key and orgid are required. If you are using RHEL8 to run the playbook (which is necessary due to the use of rhel-8 repositories), the machine should have already been subscribed in order to download the ansible executable. As long as most of the subscriptions currently give access to the two needed repos, it is not needed to unsubscribe and resuscribe, just to import the repos.

So, I made a little modification in which, if the rhel-subscription.yaml file is not found, we just log a message indicating that the current subscription will be used by the script to add the repos.

The main motivator for this change (although not the unique) is that it does not seem possible (or at least I did not find anywhere or anywho who knows how) to obtain an apikey and an orgid from a "developer" subscription, which is mainly what the people running this playbooks will be using.

2021-03-22 10:23 UTC, stuggi requested changes

2021-03-22 10:23 UTC, stuggi commented on ansible/README.md
> +`vars/rhel-subscription.yaml` is optional. If the file is not created, it will try to use your current subscription to add the corresponding repositories:
we probably should then list the repose which are required to install the required packages:

~~~
advanced-virt-for-rhel-8-x86_64-rpms                                                             Advanced Virtualization for RHEL 8 x86_64 (RPMs)
ansible-2-for-rhel-8-x86_64-rpms                                                                 Red Hat Ansible Engine 2 for RHEL 8 x86_64 (RPMs)
rhel-8-for-x86_64-appstream-rpms                                                                 Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
rhel-8-for-x86_64-baseos-rpms                                                                    Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
~~~

2021-03-22 10:23 UTC, stuggi commented on ansible/host_prep.yaml
> +      when: manual_rhel_subscription is undefined
we can move this into a block and only run both tasks `when: manual_rhel_subscription is undefined`

2021-03-22 10:23 UTC, stuggi commented on ansible/host_prep.yaml
> +
wouldn't it be enough to extend the condition of the "use secret_repo" block to check manual_rhel_subscription ?

2021-03-22 11:39 UTC, jlarriba commented on ansible/host_prep.yaml
> +
Im sorry, but I do not understand what you are proposing here. Could you give a little bit more context of what you see wrong?

2021-03-23 07:48 UTC, stuggi commented on ansible/host_prep.yaml
> +
sorry, after reading again today on what I wrote yesterday, my comment does not make sense :)

2021-03-23 07:52 UTC, stuggi approved these changes
/lgtm

2021-09-17 16:58 UTC, akiselev1 commented
I had exactly the same problem, and @abays pointed me to this PR.  It was not merged back then for some reason.
@jlarriba - let me know if you are still interested in this change. I can re-test it with the current code and resolve any merge conflicts if needed. Just give me access to your fork/branch.

2021-09-20 08:59 UTC, jlarriba commented
Hi @akiselev1 , of course I am still interested!

I think that running the ansible playbook on an already subscribed RHEL machine is a pretty common use case.

2021-09-27 15:39 UTC, abays approved these changes
/lgtm

2021-09-28 06:38 UTC, merged